### PR TITLE
add Ligue Super in ChampionishType nut not suported currently

### PR DESCRIPTION
**Pull request by EmilienMottet**
There is a new league type in mpg
Ligue Super 

It's a combination of 4 league (French, Italian, Spain, England)

Maybe later. I will try to integrate this to the bot

### CODE REVIEW

**Comment by axel3rd** [comment]
👋 @EmilienMottet, many thanks for this Pull-Request.
The build fail is not part of update (and linked to SonarQube process), I will check it.

**Comment by axel3rd** [comment]
> The build fail is not part of update (and linked to SonarQube process), I will check it.

When PR build is from:
- "internal" branch, the [Secret source is "Actions"](https://github.com/axel3rd/mpg-coach-bot/runs/8307154478?check_suite_focus=true#step:1:31) and [SONAR_TOKEN](https://github.com/axel3rd/mpg-coach-bot/runs/8307154478?check_suite_focus=true#step:14:9) is provided.
- "external" branch, the [Secret source is "None"](https://github.com/axel3rd/mpg-coach-bot/runs/8307126747?check_suite_focus=true#step:1:31) and [SONAR_TOKEN](https://github.com/axel3rd/mpg-coach-bot/runs/8307126747?check_suite_focus=true#step:14:9) is **NOT** provided 😢.

**Comment by axel3rd** [comment]
Not easy to fix => rebase "as it" and see later https://github.com/axel3rd/mpg-coach-bot/issues/244

**Comment by EmilienMottet** [comment]
Thank for merging

**Comment by axel3rd** [comment]
Available from SNAPSHOT packages (https://github.com/axel3rd/mpg-coach-bot/packages/1052515) : **mpg-coach-bot-1.11-20220912.161711-3.jar**

**Pull request merged**
